import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.*; //For file writing purposes
import javax.imageio.ImageIO;

/**
 *
 * @author Andreja
 */
public class addBooks extends javax.swing.JFrame {

    /**
     * Creates new form addBooks
     */
    
    private String arr [] = new String[4];
    private boolean checkForBookTitle;
    private boolean checkForAuthor;
    private boolean checkForGenre;
    private boolean checkForFilePath;
    private Customer customer;
    
    public addBooks(Customer customer) throws IOException{
        this.customer = customer;
        checkForBookTitle = false;
        checkForAuthor = false;
        checkForGenre = false;
        checkForFilePath = false;
        
        initComponents();
            
    }
    
    private boolean checkForValues(){
        boolean allValuesInputed = false;
        if(checkForBookTitle == true && checkForAuthor == true && checkForGenre == true && checkForFilePath == true){
            allValuesInputed = true;
        }
        
        return allValuesInputed;
    }
    
    private void appendFile() throws IOException{
        FileWriter fwriter = new FileWriter("C:\\Users\\Andreja\\Documents\\NetBeansProjects\\BookSmart\\books.txt",true);
        PrintWriter outputFile = new PrintWriter(fwriter);
        
        outputFile.println(arr[0] + "," + arr[1] + "," + arr[2]);
        
        fwriter.close();
        outputFile.close();
        
        FileWriter fwriter2 = new FileWriter("C:\\Users\\Andreja\\Documents\\NetBeansProjects\\BookSmart\\genres.txt",true);
        PrintWriter outputFile2 = new PrintWriter(fwriter2);
        
        outputFile2.println(arr[2] + " " + arr[2]);
        
        fwriter2.close();
        outputFile2.close();
    }
    
    private void addFileImage() throws IOException{
        String filePath = "C:\\Users\\Andreja\\Documents\\NetBeansProjects\\BookSmart\\images";
        
        File files [] = new File(filePath).listFiles();
        filePath += "\\" + (files.length + 1) + ".jpg";
        
        //reads input image
        File inputFile = new File(arr[3]);
        System.out.println(inputFile.exists());
        BufferedImage inputImage = ImageIO.read(inputFile);
        File outputFile = new File(filePath);
       
        //creates ouput image
        BufferedImage outputImage = new BufferedImage(229,293,inputImage.getType());
        
        //Scales the input image to the output image
        Graphics2D g2d = outputImage.createGraphics();
        g2d.drawImage(inputImage, 0, 0, 229, 293, null);
        g2d.dispose();
        
        //Extracts extension of output file
        String formatName = filePath.substring(filePath.lastIndexOf(".") + 1);
        
        //writes to output file
        ImageIO.write(outputImage,formatName, outputFile);
        
        image.setIcon(new javax.swing.ImageIcon(filePath));     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        bookGenreInput = new javax.swing.JTextField();
        bookTitleInput = new javax.swing.JTextField();
        bookAuthorInput = new javax.swing.JTextField();
        filePathInput = new javax.swing.JTextField();
        filePathInputButton = new javax.swing.JButton();
        bookTitleInputButton = new javax.swing.JButton();
        authorInputButton = new javax.swing.JButton();
        genreInputButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        logo = new javax.swing.JMenu();
        recommended = new javax.swing.JMenu();
        random = new javax.swing.JMenu();
        browse = new javax.swing.JMenu();
        booksYouveRated = new javax.swing.JMenu();
        mainMenu = new javax.swing.JMenu();
        clubs = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(214, 217, 223));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Add Books");
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andreja\\Documents\\NetBeansProjects\\BookSmart\\src\\booksmart\\logo_Menu.png")); // NOI18N

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(214, 217, 223));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Input:");
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(214, 217, 223));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Book Image:");
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        bookGenreInput.setText("Genre");
        bookGenreInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookGenreInputActionPerformed(evt);
            }
        });

        bookTitleInput.setText("Book Title");
        bookTitleInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTitleInputActionPerformed(evt);
            }
        });

        bookAuthorInput.setText("Author");
        bookAuthorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAuthorInputActionPerformed(evt);
            }
        });

        filePathInput.setText("File Path to Image");
        filePathInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathInputActionPerformed(evt);
            }
        });

        filePathInputButton.setText("Input");
        filePathInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathInputButtonActionPerformed(evt);
            }
        });

        bookTitleInputButton.setText("Input");
        bookTitleInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTitleInputButtonActionPerformed(evt);
            }
        });

        authorInputButton.setText("Input");
        authorInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorInputButtonActionPerformed(evt);
            }
        });

        genreInputButton.setText("Input");
        genreInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreInputButtonActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("logo_Menu.png"))); // NOI18N
        jMenuBar1.add(logo);

        recommended.setText("Recommended");
        recommended.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        recommended.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recommendedMouseClicked(evt);
            }
        });
        jMenuBar1.add(recommended);

        random.setText("Random");
        random.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        random.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                randomMouseClicked(evt);
            }
        });
        jMenuBar1.add(random);

        browse.setText("Browse");
        browse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        browse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browseMouseClicked(evt);
            }
        });
        jMenuBar1.add(browse);

        booksYouveRated.setText("Books You've Rated");
        booksYouveRated.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        booksYouveRated.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksYouveRatedMouseClicked(evt);
            }
        });
        jMenuBar1.add(booksYouveRated);

        mainMenu.setText("Main Menu");
        mainMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(mainMenu);

        clubs.setText("Clubs");
        clubs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clubs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clubsMouseClicked(evt);
            }
        });
        jMenuBar1.add(clubs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(filePathInputButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(filePathInput, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(genreInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bookGenreInput, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(authorInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bookAuthorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bookTitleInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bookTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookTitleInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookAuthorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookGenreInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genreInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filePathInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filePathInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recommendedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recommendedMouseClicked
        new Recommend(this.customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_recommendedMouseClicked

    private void randomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_randomMouseClicked
        new RandomBook(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_randomMouseClicked

    private void browseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseMouseClicked
        new BrowseMenu(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_browseMouseClicked

    private void booksYouveRatedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksYouveRatedMouseClicked
        try {
            new SeeRated(this.customer).setVisible(true);
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        this.setVisible(false);
    }//GEN-LAST:event_booksYouveRatedMouseClicked

    private void mainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseClicked
        try {
            new mainMenu(this.customer).setVisible(true);
        } catch (Exception e) {
            Logger.getLogger(addBooks.class.getName()).log(Level.SEVERE, null, e);
        }
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuMouseClicked

    private void clubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clubsMouseClicked
        try{
            new Friends_Page(this.customer, null).setVisible(true);
        }catch(Exception e){
            e.printStackTrace();
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_clubsMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void bookGenreInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookGenreInputActionPerformed
        
    }//GEN-LAST:event_bookGenreInputActionPerformed

    private void bookTitleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTitleInputActionPerformed
        
    }//GEN-LAST:event_bookTitleInputActionPerformed

    private void bookAuthorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAuthorInputActionPerformed
        
    }//GEN-LAST:event_bookAuthorInputActionPerformed

    private void filePathInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathInputActionPerformed
        
    }//GEN-LAST:event_filePathInputActionPerformed

    private void bookTitleInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTitleInputButtonActionPerformed
        arr[0] = bookTitleInput.getText();
        checkForBookTitle = true;
        if(checkForValues() == true){
            try {
                appendFile();
                addFileImage();
            } catch (IOException ex) {
                Logger.getLogger(addBooks.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bookTitleInputButtonActionPerformed

    private void authorInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorInputButtonActionPerformed
        arr[1] = bookAuthorInput.getText();
        checkForAuthor = true;
        if(checkForValues() == true){
            try {
                appendFile();
                addFileImage();
            } catch (IOException ex) {
                Logger.getLogger(addBooks.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_authorInputButtonActionPerformed

    private void genreInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreInputButtonActionPerformed
        arr[2] = bookGenreInput.getText();
        checkForGenre = true;
        if(checkForValues() == true){
            try {
                appendFile();
                addFileImage();
            } catch (IOException ex) {
                Logger.getLogger(addBooks.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_genreInputButtonActionPerformed

    private void filePathInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathInputButtonActionPerformed
        arr[3] = filePathInput.getText();
        checkForFilePath = true;
        if(checkForValues() == true){
            try {
                appendFile();
                addFileImage();
            } catch (IOException ex) {
                Logger.getLogger(addBooks.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_filePathInputButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(addBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(addBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(addBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(addBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             try {
    //                 new addBooks().setVisible(true);
    //             } catch (IOException ex) {
    //                 Logger.getLogger(addBooks.class.getName()).log(Level.SEVERE, null, ex);
    //             }
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorInputButton;
    private javax.swing.JTextField bookAuthorInput;
    private javax.swing.JTextField bookGenreInput;
    private javax.swing.JTextField bookTitleInput;
    private javax.swing.JButton bookTitleInputButton;
    private javax.swing.JMenu booksYouveRated;
    private javax.swing.JMenu browse;
    private javax.swing.JMenu clubs;
    private javax.swing.JTextField filePathInput;
    private javax.swing.JButton filePathInputButton;
    private javax.swing.JButton genreInputButton;
    private javax.swing.JLabel image;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JMenu logo;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenu random;
    private javax.swing.JMenu recommended;
    // End of variables declaration//GEN-END:variables
}