/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package mysurvey;

/**
* This page both prompts the registering user for and stores their taste in literature, giving the book recommendation algorithm a more informed starting point
* Author: Luke Cihra
* Date Created: October 1, 2020
* Last Modified: October 9, 2020
* Assumptions: User input will be 3 of the type being asked for, each separated by a comma and a space
*/

//allows implementation of jFrame
import javax.swing.JOptionPane;
//allows page to write to file
import java.io.FileWriter;

public class bookSurvey extends javax.swing.JFrame {

    /**x
     * Creates new form bookSurvey
     */
    public bookSurvey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));

        jTextField1.setText("Type here...");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jTextField2.setText("Type here...");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField3.setText("Type here...");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel1.setText("List your 3 favourite genres.");

        jLabel2.setText("List your 3 favourite books.");

        jLabel3.setText("List your 3 favourite authors.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 55, 53));
        jLabel4.setText("Survey");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/logo2.png"))); // NOI18N

        jButton2.setText("Skip");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>                        

    /**
    * Takes user's answers in registration survey and stores them in external data file
    * @param a User's 3 favourite genres
    * @param b User's 3 favourite books
    * @param c User's 3 favourite authors
    */
    public void setSurveyData(String a, String b, String c){
        //preparing to write to external file
        final String FILENAME = "SurveyData.txt";
        FileWriter fw;
        
        //try-catch createst external file and writes user data from survey to it
        try{
            fw = new FileWriter(FILENAME, true);

            fw.write(a + "," + b + "," + c + "\n");//writes user input on one line in external file

            fw.close();//closes fileWriter to conserve memory
        }catch(Exception e){
            e.printStackTrace();
        }//end of try-catch statement
    }//end of setSurveyData method    
    
    /**
    * Makes jTextField1 (where user enters favourite genres) blank when clicked on for first time by user
    */  
    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {                                        
        if (jTextField1.getText().equals("Type here...")){
            jTextField1.setText("");
        }//end of if statement
    }//end of method jTextField1Gained                                      

    /**
    * If user clicks on jTextField1 but doesn't type anything and clicks off, revert textfield back to displaying sample text "Type here"
    */ 
    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {                                      
        if (jTextField1.getText().equals("")){
            jTextField1.setText("Type here...");
        }//end of if statement
    }//end of method jTextField1FocusLost                                      

    /**
    * Makes jTextField2 (where user enters favourite books) blank when clicked on for first time by user
    */     
    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {                                        
        if (jTextField2.getText().equals("Type here...")){
            jTextField2.setText("");
        }//end of if statement
    }//end of method jTextField2FocusGained                                      

    /**
    * If user clicks on jTextField1 but doesn't type anything and clicks off, revert textfield back to displaying sample text "Type here"
    */ 
    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {                                      
        if (jTextField2.getText().equals("")){
            jTextField2.setText("Type here...");
        }//end of if statement
    }//end of method jTextField2FocusLost                                      

    /**
    * Makes jTextField3 (where user enters favourite authors) blank when clicked on for first time by user
    */  
    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {                                        
        if (jTextField3.getText().equals("Type here...")){
            jTextField3.setText("");
        }//end of if statement
    }//end of method jTextField3FocusGained                                       

    /**
    * If user clicks on jTextField1 but doesn't type anything and clicks off, revert textfield back to displaying sample text "Type here"
    */ 
    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {                                      
        if (jTextField3.getText().equals("")){
            jTextField3.setText("Type here...");
        }//end of if statement
    }//end of method jTextField3FocusLost                                     

    /**
    * instantiates setSurveyData with user's answers when user clicks "Submit" button
    */ 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    setSurveyData(jTextField1.getText(), jTextField2.getText(), jTextField3.getText());
    JOptionPane.showMessageDialog(null, "Your Survey has been saved!");
    }                                        

    /**
    * instantiates setSurveyData with nothing if they choose to skip the survey
    */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        setSurveyData("none", "none", "none");
        JOptionPane.showMessageDialog(null, "You have been fully registered!");
    }//end of method jButton2ActionPerformed                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookSurvey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookSurvey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookSurvey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookSurvey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookSurvey().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration                   
}//end of class BookSurvey
