/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booksmart;

/**
 *
 * @author Luke
 */

import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;


public class BrowseMenu extends javax.swing.JFrame {
 
    File bookStuff = new File("C:\\Users\\Andreja\\Documents\\NetBeansProjects\\BookSmart\\books.txt");
    Scanner bookInfo;
    
    private Customer customer;
    /**
     * Creates new form BrowseMenu
     */
    public BrowseMenu(Customer customer)  {
        this.customer = customer;
        initComponents();
        try {
            this.bookInfo = new Scanner(bookStuff);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BrowseMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void readReset() throws IOException {
        File bookStuff = new File("C:\\Users\\Andreja\\Documents\\NetBeansProjects\\BookSmart\\books.txt");
        bookInfo = new Scanner(bookStuff); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        searchBar1 = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLogo = new javax.swing.JMenu();
        menuRecommended = new javax.swing.JMenu();
        menuRandom = new javax.swing.JMenu();
        menuBrowse = new javax.swing.JMenu();
        menuRated = new javax.swing.JMenu();
        menuAdd = new javax.swing.JMenu();
        menuClubs = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(67, 55, 53));
        jLabel2.setText("Browse");

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        searchBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBar1ActionPerformed(evt);
            }
        });

        searchButton1.setText("Go To Book");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksmart/logo_Menu.png"))); // NOI18N
        menuLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLogo);

        menuRecommended.setText("Recommended");
        menuRecommended.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuRecommended.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRecommendedMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRecommended);

        menuRandom.setText("Random");
        menuRandom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuRandom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRandomMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRandom);

        menuBrowse.setText("Browse");
        menuBrowse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuBrowse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBrowseMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBrowse);

        menuRated.setText("Books You've Rated");
        menuRated.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuRated.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRatedMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRated);

        menuAdd.setText("Add Books");
        menuAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAddMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAdd);

        menuClubs.setText("Clubs");
        menuClubs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(menuClubs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton)))
                        .addGap(0, 311, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            readReset();
        } catch (IOException ex) {
            Logger.getLogger(BrowseMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea2.setText("");
        String searched = "";
        searched = searchBar.getText();
        String theTitle = "";
        while (bookInfo.hasNextLine()) {
            theTitle =  bookInfo.nextLine();

            String [] title = theTitle.split(",");

            if(theTitle.toLowerCase().contains(searched.toLowerCase())){
                jTextArea2.setText(jTextArea2.getText() + String.join("", (title[0] + " by: " + title[1])) + "\n");
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void menuLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoMouseClicked
        
    }//GEN-LAST:event_menuLogoMouseClicked

    private void menuRecommendedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRecommendedMouseClicked
        
    }//GEN-LAST:event_menuRecommendedMouseClicked

    private void menuRandomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRandomMouseClicked
        
    }//GEN-LAST:event_menuRandomMouseClicked

    private void menuBrowseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBrowseMouseClicked
        
    }//GEN-LAST:event_menuBrowseMouseClicked

    private void menuRatedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRatedMouseClicked
        
    }//GEN-LAST:event_menuRatedMouseClicked

    private void menuAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAddMouseClicked
        
    }//GEN-LAST:event_menuAddMouseClicked

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBar1ActionPerformed
        
    }//GEN-LAST:event_searchBar1ActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt)  {//GEN-FIRST:event_searchButton1ActionPerformed
        try {
            readReset();
        } catch (IOException ex) {
            Logger.getLogger(BrowseMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        String searched = "";
        searched = searchBar1.getText();
        String theTitle = "";
        int lineNumber = 0;
        while (bookInfo.hasNextLine()) {
            theTitle =  bookInfo.nextLine();
            lineNumber += 1;

            String [] title = theTitle.split(",");
            
            System.out.println(title[0]);

            if(title[0].toLowerCase().equals(searched.toLowerCase())){
                try {
                    new BookPage(title[0], title[1], lineNumber,customer).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(BrowseMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);
                break;
            }
        }
    }//GEN-LAST:event_searchButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //try {
              //     new BrowseMenu().setVisible(true);
              //  } catch (FileNotFoundException ex) {
               //     Logger.getLogger(BrowseMenu.class.getName()).log(Level.SEVERE, null, ex);
             //   }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JMenu menuAdd;
    private javax.swing.JMenu menuBrowse;
    private javax.swing.JMenu menuClubs;
    private javax.swing.JMenu menuLogo;
    private javax.swing.JMenu menuRandom;
    private javax.swing.JMenu menuRated;
    private javax.swing.JMenu menuRecommended;
    private javax.swing.JTextField searchBar;
    private javax.swing.JTextField searchBar1;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    // End of variables declaration//GEN-END:variables
}
