//import nessessary libraries
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 * Creates a help page for the user
 * @author jaimoraes
 */
public class HelpPage extends javax.swing.JFrame {

    private File helpPage;
    /**
     * Creates new form HelpPage
     *Initiates components, sets the text of the help window, set the frame to visible
     */
    public HelpPage(String helpPath) throws FileNotFoundException {
        initComponents();
        this.helpPage= new File(helpPath);
        this.load();
        this.setVisible(true);
    }//Constructor

    /**
    *NOT COMMENTED AS THIS IS AUTOMATIC
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    
//PRANAV please change the menu font- but please dont mess too much with the size. ty

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        DoNotUse = new javax.swing.JMenu();
        BooksRated = new javax.swing.JMenu();
        AddBooks = new javax.swing.JMenu();
        Chats = new javax.swing.JMenu();
        BrowseGeneral = new javax.swing.JMenu();
        RandomBook = new javax.swing.JMenu();
        Browse = new javax.swing.JMenu();
        Recommended = new javax.swing.JMenu();
        MainMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Help Page");

        DoNotUse.setIcon(new javax.swing.ImageIcon(getClass().getResource("logo_Menu.png"))); // NOI18N
        jMenuBar1.add(DoNotUse);

        BooksRated.setText("Books you've rated");
        BooksRated.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BooksRated.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksRatedMouseClicked(evt);
            }
        });
        jMenuBar1.add(BooksRated);

        AddBooks.setText("Add Books");
        AddBooks.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        AddBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBooksMouseClicked(evt);
            }
        });
        jMenuBar1.add(AddBooks);

        Chats.setText("Chats");
        Chats.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Chats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChatsMouseClicked(evt);
            }
        });
        jMenuBar1.add(Chats);

        BrowseGeneral.setText("Browse & Other");
        BrowseGeneral.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        RandomBook.setText("Random Book");
        RandomBook.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        RandomBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RandomBookMouseClicked(evt);
            }
        });
        BrowseGeneral.add(RandomBook);

        Browse.setText("Browse");
        Browse.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        Browse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrowseMouseClicked(evt);
            }
        });
        BrowseGeneral.add(Browse);

        Recommended.setText("Recomended");
        Recommended.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        Recommended.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecommendedMouseClicked(evt);
            }
        });
        BrowseGeneral.add(Recommended);

        jMenuBar1.add(BrowseGeneral);

        MainMenu.setText("Main Menu");
        MainMenu.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuBar1.add(MainMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    
//PRANAV add stuff for this menu
    private void BrowseMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void RecommendedMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void RandomBookMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void ChatsMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void AddBooksMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void BooksRatedMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
    *Loads the help file to the screen
    */
    private void load() throws FileNotFoundException{
        String toPrint="";
        Scanner sc= new Scanner(helpPage);
        while(sc.hasNextLine())
            toPrint+="\n"+sc.nextLine();
        this.jTextArea1.setText(toPrint);
    }//load

    // Variables declaration - do not modify                     
    private javax.swing.JMenu AddBooks;
    private javax.swing.JMenu BooksRated;
    private javax.swing.JMenu Browse;
    private javax.swing.JMenu BrowseGeneral;
    private javax.swing.JMenu Chats;
    private javax.swing.JMenu DoNotUse;
    private javax.swing.JMenu MainMenu;
    private javax.swing.JMenu RandomBook;
    private javax.swing.JMenu Recommended;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}//helpPage class/ jFrame subclass
